# Generated by Django 2.2 on 2019-12-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20191213_0530'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(default='Unknown', max_length=50)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='snippet',
            name='name',
            field=models.CharField(default='unknown', max_length=200),
            preserve_default=False,
        ),
    ]
