# Generated by Django 2.2 on 2019-12-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_allnode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(default='Unknown', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='allnode',
            name='x',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='allnode',
            name='y',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
