# Generated by Django 2.2 on 2020-01-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_auto_20191215_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culc_bit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.IntegerField(default=0, max_length=50)),
            ],
        ),
    ]
